theme = "tokyonight_storm"

[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"

[keys.normal]
a = ["append_mode", "collapse_selection"]
i = ["insert_mode", "collapse_selection"]
C-c = ["collapse_selection", "keep_primary_selection"]
"\\" = "toggle_comments"

[keys.insert]
C-c = ["collapse_selection", "keep_primary_selection", "normal_mode"]

[keys.select]
C-c = ["collapse_selection", "keep_primary_selection", "normal_mode"]
"\\" = "toggle_comments"
